jobs:
  validation:
    name: Validation
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v1
name: Validate Gradle Wrapper
on:
  repository_dispatch:
    types: trigger-ga___gradle-wrapper-validation.yml
