jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    name: Build project
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repo
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Cache Gradle Files
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches/

          ~/.gradle/wrapper/

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Run Gradle tasks
      run: ./gradlew build
name: Merge checks
on:
  repository_dispatch:
    types: trigger-ga___merge-check.yml
